actual_output: 469
comment: "TEST number of agent crashes on |BL1|.\nGIVEN |0| agent crashes.\nWHEN |469|\
  \ agent crashes.\nTHEN test case result is |False|.\nOUTPUT of |show agent logs\
  \ crash| is:\n===> /var/log/agents/ConfigAgent-1892 Thu Feb 24 15:24:36 2022 <===\n\
  ===== Output from /usr/bin/ConfigAgent [] (PID=1892) started Feb 24 15:24:03.454129\
  \ ===\nNo matching paths found for pattern: /usr/lib/SysdbMountProfiles/ConfigMountProfile\n\
  CLI Exception: Internal error <type 'exceptions.ValueError'>: Invalid value for\
  \ 'server': 'unspecified'\nCLI Exception: Traceback (most recent call last):\nCLI\
  \ Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\", line 486, in\
  \ _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 1084, in runTokenizedCmd\nCLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 176, in wrapper\n\
  CLI Exception:     return func( *args, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 910, in _invokeValueFunc\nCLI Exception:     return valueFunc( modelet, **kargs\
  \ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\",\
  \ line 1175, in __call__\nCLI Exception:     jsonValue, self.cliModel_ )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line 966, in runShowCommand\n\
  CLI Exception:     return _runShowCommandInternal( mode, showCmdFunc, jsonValue,\
  \ cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nERROR: [Errno 32] Broken pipe\nTraceback (most recent\
  \ call last):\n  File \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\", line\
  \ 107, in processRequest\n    self._processRequestInternal( request )\n  File \"\
  /usr/lib/python2.7/site-packages/JsonRpcBase.py\", line 137, in _processRequestInternal\n\
  \    self._processRequestNonStreaming( procedure, params )\n  File \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\"\
  , line 173, in _processRequestNonStreaming\n    os.write( self.outputFd_, i )\n\
  OSError: [Errno 32] Broken pipe\nERROR: [Errno 32] Broken pipe\nTraceback (most\
  \ recent call last):\n  File \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\"\
  , line 107, in processRequest\n    self._processRequestInternal( request )\n  File\
  \ \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\", line 137, in _processRequestInternal\n\
  \    self._processRequestNonStreaming( procedure, params )\n  File \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\"\
  , line 173, in _processRequestNonStreaming\n    os.write( self.outputFd_, i )\n\
  OSError: [Errno 32] Broken pipe\nERROR: [Errno 32] Broken pipe\nTraceback (most\
  \ recent call last):\n  File \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\"\
  , line 107, in processRequest\n    self._processRequestInternal( request )\n  File\
  \ \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\", line 137, in _processRequestInternal\n\
  \    self._processRequestNonStreaming( procedure, params )\n  File \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\"\
  , line 173, in _processRequestNonStreaming\n    os.write( self.outputFd_, i )\n\
  OSError: [Errno 32] Broken pipe\nERROR: [Errno 32] Broken pipe\nTraceback (most\
  \ recent call last):\n  File \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\"\
  , line 107, in processRequest\n    self._processRequestInternal( request )\n  File\
  \ \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\", line 137, in _processRequestInternal\n\
  \    self._processRequestNonStreaming( procedure, params )\n  File \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\"\
  , line 173, in _processRequestNonStreaming\n    os.write( self.outputFd_, i )\n\
  OSError: [Errno 32] Broken pipe\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nERROR: [Errno 32] Broken pipe\nTraceback (most recent\
  \ call last):\n  File \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\", line\
  \ 107, in processRequest\n    self._processRequestInternal( request )\n  File \"\
  /usr/lib/python2.7/site-packages/JsonRpcBase.py\", line 137, in _processRequestInternal\n\
  \    self._processRequestNonStreaming( procedure, params )\n  File \"/usr/lib/python2.7/site-packages/JsonRpcBase.py\"\
  , line 173, in _processRequestNonStreaming\n    os.write( self.outputFd_, i )\n\
  OSError: [Errno 32] Broken pipe\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\nCLI Exception: Internal error <type 'exceptions.ValueError'>:\
  \ Invalid value for 'server': 'unspecified'\nCLI Exception: Traceback (most recent\
  \ call last):\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliApi.py\"\
  , line 486, in _execute\nCLI Exception:     fromCapi=True )\nCLI Exception:   File\
  \ \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 1084, in runTokenizedCmd\n\
  CLI Exception:     authz=aaa, acct=aaa )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\"\
  , line 176, in wrapper\nCLI Exception:     return func( *args, **kwargs )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/BasicCliSession.py\", line 910, in _invokeValueFunc\n\
  CLI Exception:     return valueFunc( modelet, **kargs )\nCLI Exception:   File \"\
  /usr/lib/python2.7/site-packages/ShowCommand.py\", line 1175, in __call__\nCLI Exception:\
  \     jsonValue, self.cliModel_ )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 966, in runShowCommand\nCLI Exception:     return _runShowCommandInternal(\
  \ mode, showCmdFunc, jsonValue, cliModel )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 860, in _runShowCommandInternal\nCLI Exception:     result = showCmdFunc()\n\
  CLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\", line\
  \ 1002, in showCmdFunc\nCLI Exception:     return _runShowCommandFunction( mode,\
  \ valueFunction, prepareFunction, kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/ShowCommand.py\"\
  , line 628, in _runShowCommandFunction\nCLI Exception:     return valueFunction(\
  \ mode, **kwargs )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliPlugin/Ntp.py\"\
  , line 168, in doShowNtpStatus\nCLI Exception:     _details=details )\nCLI Exception:\
  \   File \"/usr/lib/python2.7/site-packages/CliModel.py\", line 871, in __init__\n\
  CLI Exception:     setAttr( attr, value )\nCLI Exception:   File \"/usr/lib/python2.7/site-packages/CliModel.py\"\
  , line 907, in __setattr__\nCLI Exception:     raise ValueError( \"Invalid value\
  \ for %r: %r\" % ( name, value ) )\nCLI Exception: ValueError: Invalid value for\
  \ 'server': 'unspecified'\n\n\n.\n"
description: Verifies the agents logs crash is empty
dut: BL1
expected_output: 0
fail_or_skip_reason: '

  On router |BL1| has |469| agent crashes correct number of agent crashes is |0|.

  '
name: test_if_there_is_agents_have_crashed_on_
output_msg: '

  On router |BL1| has |469| agent crashes correct number of agent crashes is |0|.

  '
show_cmd: show agent logs crash
test_id: null
test_result: false
test_suite: test_system.py
